#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <contact>;
!slot <callPhone>;
!slot <contactt>;
!slot <callPhonee>;
!start <callStart>;
<callStart>:<contact><callPhone> | <contactt>;
<contact>:打开|关闭|开始;
<callPhone>:镜子|游戏|学习|录制;
<contactt>:下一段|返回;